services:
  - type: web
    name: chat-analyzer
    env: docker
    plan: free
    branch: main
    repo: https://github.com/dansy-rodz/chat-analyzer
    dockerfilePath: Dockerfile
    healthCheckPath: /
